name: Sync Drupal Core Tags

on:
  schedule:
    - cron: "0 * * * *" # run hourly
  workflow_dispatch: # allow manual trigger

jobs:
  sync-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # needed for tag operations

      - name: Fetch drupal/core tags
        run: |
          git clone --quiet --bare https://github.com/drupal/core.git drupal-core.git
          cd drupal-core.git
          git tag > /tmp/drupal-tags.txt

      - name: Compare tags
        id: compare
        run: |
          git tag > /tmp/local-tags.txt
          # Get the latest tag from drupal/core and local, sorted by version
          LATEST_DRUPAL_TAG=$(sort -V /tmp/drupal-tags.txt | tail -n 1)
          LATEST_LOCAL_TAG=$(sort -V /tmp/local-tags.txt | tail -n 1)

          # Only create a new tag if the drupal/core tag is newer
          if [ "$LATEST_DRUPAL_TAG" != "$LATEST_LOCAL_TAG" ]; then
            echo "new_tag=$LATEST_DRUPAL_TAG" >> $GITHUB_OUTPUT
          fi

      - name: Create new tag in this repo
        if: steps.compare.outputs.new_tag != ''
        run: |
          TAG=${{ steps.compare.outputs.new_tag }}
          echo "Creating new tag: $TAG"
          git tag $TAG
          git push origin $TAG
